@startsalt mcq-not-quite
skinparam backgroundColor transparent
skinparam defaultFontName Monospaced

{+
  <&x> Not quite
  ==
.
  " Correct answer is "
.
  "      101010       "
.
.
.
.
.
  [ Continue ]
}
@endsalt