spring.application.name=boduha-server
application.version=@project.version@

server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true
server.forward-headers-strategy=native